---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: src/pages/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: document
  path: src/pages/index.md
  label: Homepage
- type: document
  path: src/pages/studio.md
  label: About
- type: document
  path: src/site/settings.md
  label: Site settings
upload_dir: static/img
public_path: static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
