backend:
  branch: master
  name: github
  repo: RandomStudio/random-studio
  use_graphql: true
publish_mode: editorial_workflow
media_folder: public/img
public_folder: /img
collections:
  - name: project
    label: Project
    folder: src/content/projects
    create: true
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: templateKey
        widget: hidden
        default: Project
      - label: Title
        name: title
        widget: text
      - label: Intro
        name: intro
        buttons:
          - link
        widget: markdown
      - label: "Priority on homepage"
        name: priority
        required: false
        value_type: float
        widget: nonEmptyStringableNumber
      - label: Content
        name: content
        widget: list
        fields:
          - label: Image
            name: image
            required: false
            widget: image
          - label: Alt tag image
            name: alt
            required: false
            widget: string
          - label: Video
            name: video
            required: false
            collapsed: true
            widget: object
            fields:
              - label: "Video URL"
                name: url
                required: false
                widget: text
              - label: "Will autoplay"
                name: autoplay
                required: false
                default: false
                widget: boolean
              - label: "Show controls"
                name: hasControls
                required: false
                default: false
                widget: boolean
              - label: "Loop video"
                name: loops
                required: false
                default: true
                widget: boolean
              - label: Muted
                name: isMuted
                required: false
                default: true
                widget: boolean
              - label: "Always Muted"
                name: isAlwaysMuted
                required: false
                widget: boolean
                default: false
                hint: "Check this if the video has no audio for example."
          - label: Carousel
            name: carousel
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - label: Image
                    name: image
                    required: false
                    widget: image
                  - label: Image Caption
                    name: caption
                    widget: markdown
                    required: false
              - label: Video
                name: video
                required: false
                widget: object
                fields:
                  - label: "Video URL"
                    name: url
                    required: false
                    widget: text
                  - label: Video Caption
                    name: caption
                    widget: markdown
                    required: false
                  - label: Muted
                    name: isMuted
                    required: false
                    default: true
                    widget: hidden
          - label: Caption
            name: caption
            required: false
            widget: markdown
          - label: Width
            name: width
            required: false
            value_type: float
            widget: nonEmptyStringableNumber
          - label: "Margin Top"
            name: marginTop
            default: 0
            value_type: float
            widget: nonEmptyStringableNumber
          - label: "Margin Left"
            name: marginLeft
            default: 0
            value_type: float
            widget: nonEmptyStringableNumber
          - label: "z-index"
            name: zIndex
            default: 0
            value_type: number
            widget: nonEmptyStringableNumber
      - label: Related Projects
        name: relatedProjects
        widget: object
        required: false
        fields:
          - label: Block Title
            name: blockTitle
            widget: string
            required: false
          - label: Projects
            name: projects
            widget: list
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Subtitle
                name: subtitle
                widget: string
                required: false
              - label: Image
                name: image
                widget: image
                required: true
              - label: Project
                name: project
                hint: "This is the url assignment for the related project"
                widget: relation
                required: true
                collection: "project"
                search_fields: ["title"]
                # valueField: '{{slug}}' Currently not supproted
                value_field: "title"
                display_fields: ["title"]
      - label: Credits
        name: credits
        widget: list
        fields:
          - label: Key
            name: key
            widget: text
          - label: Value
            name: value
            widget: text
      - label: OpenGraph tags
        name: opengraph
        widget: object
        fields:
          - label: "Title"
            name: ogTitle
            required: false
            value_type: string
            widget: text
          - label: "Description"
            name: ogDescription
            required: false
            value_type: string
            widget: text
          - label: "Image"
            name: ogImage
            required: false
            value_type: string
            widget: image
  - name: pages
    label: Pages
    files:
      - file: src/content/index.md
        label: "Home Page"
        name: index
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: index
          - label: "Logo Position"
            name: layout
            widget: select
            options:
              - { label: center, value: center }
              - { label: Top, value: top }
            default: ["center"]
          - label: "Video URL"
            name: video
            required: true
            widget: text
          - label: Collaboration Credits
            name: collaborationCredits
            required: false
            widget: object
            fields:
              - label: Collaborator
                name: collaborator
                widget: text
              - label: "Referral URL"
                name: url
                required: false
                widget: text
          - label: Intro
            name: intro
            widget: markdown
          - label: Middle
            name: middle
            widget: markdown
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Homepage Caption
                name: caption
                required: false
                widget: text
              - label: Thumbnail
                name: thumbnail
                widget: object
                fields:
                  - label: Image
                    name: image
                    required: false
                    widget: image
                  - label: "Video URL"
                    name: video
                    required: false
                    widget: text
                  - label: Width
                    name: width
                    required: false
                    value_type: float
                    widget: nonEmptyStringableNumber
                  - label: "Margin Top"
                    name: marginTop
                    default: 0
                    value_type: float
                    widget: nonEmptyStringableNumber
                  - label: "Margin Left"
                    name: marginLeft
                    default: 0
                    value_type: float
                    widget: nonEmptyStringableNumber
              - name: project
                widget: relation
                required: false
                collection: "project"
                search_fields: ["title"]
                value_field: "title"
                display_fields: ["title"]
      - file: src/content/projects.md
        label: "Projects Page"
        name: projects
        fields:
          - label: "Template Key"
            name: templateKey
            widget: hidden
            default: projects
      - file: src/content/studio.md
        label: "Studio page"
        name: studio
        fields:
          - label: "Template key"
            name: templateKey
            widget: hidden
            default: studio
          - label: Title
            name: title
            widget: string
            default: "Random Studio"
          - label: "Intro Block"
            name: introBlock
            widget: list
            fields:
              - label: Copy
                name: copy
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: Video
                name: video
                widget: file
                hint: "Adding a video will replace the image"
                required: false
                allow_multiple: false
                media_library:
                  config:
                    multiple: false

          - label: Services
            name: services
            widget: object
            fields:
              - label: Title
                name: title
                widget: text
              - label: "List of Services"
                name: list
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: text
                  - label: Copy
                    name: copy
                    widget: text
                  - label: Image
                    name: image
                    widget: image

          - label: "Our Skillset"
            name: skillset
            widget: list
            field:
              label: Skill
              name: skill
              widget: string

          - label: "Studio impression"
            name: studioImpression
            widget: object
            fields:
              - label: Title
                name: title
                default: "Studio Impressions"
                widget: text
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                    media_library:
                      config:
                        multiple: true

          - label: "Job Openings"
            name: jobOpenings
            widget: list
            fields:
              - label: "Job title"
                name: jobTitle
                widget: string
                default: Job function title
              - label: "Job URL"
                name: jobURL
                widget: string
                default: https://randomstudio.bamboohr.com/jobs/view.php?id=<ID here>
              - label: "Job description"
                name: jobDescription
                widget: text
                default: Job description
              - label: "Show this project live"
                name: jobIsVisible
                widget: boolean
                default: false
