import { Color } from 'three';

export const DAY_NIGHT_CYCLE_STAGE = {
  DEEP_NIGHT: 'Deep Night (Astronomical Night)',
  ASTRONOMICAL_TWILIGHT: 'Astronomical Twilight',
  NAUTICAL_TWILIGHT: 'Nautical Twilight',
  CIVIL_TWILIGHT: 'Civil Twilight',
  SUNRISE: 'Sunrise',
  SUNSET: 'Sunset',
  EARLY_MORNING: 'EARLY_MORNING',
  MID_MORNING: 'MID_MORNING',
  LATE_MORNING: 'LATE_MORNING',
  NOON: 'NOON',
} as const;

export const DAY_NIGHT_CYCLE_STAGES = [
  {
    elevation: -18,
    name: DAY_NIGHT_CYCLE_STAGE.DEEP_NIGHT,
    skyColor: new Color(0x181818),
    lightColor: new Color(0x181818),
    intensity: 0.05,
    turbidity: 2,
    rayleigh: 0.2,
    mieCoefficient: 0.005,
  },
  {
    elevation: -12,
    name: DAY_NIGHT_CYCLE_STAGE.ASTRONOMICAL_TWILIGHT,
    skyColor: new Color(0x483d8b),
    lightColor: new Color(0x483d8b),
    intensity: 0.1,
    turbidity: 6,
    rayleigh: 0.5,
    mieCoefficient: 0.0008,
  },
  {
    elevation: -6,
    name: DAY_NIGHT_CYCLE_STAGE.NAUTICAL_TWILIGHT,
    skyColor: new Color(0x6495ed),
    lightColor: new Color(0x6495ed),
    intensity: 0.3,
    turbidity: 10,
    rayleigh: 1,
    mieCoefficient: 0.001,
  },
  {
    elevation: -0.3,
    name: DAY_NIGHT_CYCLE_STAGE.CIVIL_TWILIGHT,
    skyColor: new Color(0xffdab9),
    lightColor: new Color(0xffdab9),
    intensity: 0.5,
    turbidity: 20,
    rayleigh: 2,
    mieCoefficient: 0.002,
  },
  {
    elevation: 0,
    name: DAY_NIGHT_CYCLE_STAGE.SUNRISE,
    skyColor: new Color(0xffa07a),
    lightColor: new Color(0xffa07a),
    intensity: 0.8,
    turbidity: 10,
    rayleigh: 3,
    mieCoefficient: 0.005,
  },
  {
    elevation: 0.1,
    name: DAY_NIGHT_CYCLE_STAGE.EARLY_MORNING,
    skyColor: new Color(0xffa07a), // Soft, warm morning light
    lightColor: new Color(0xffa07a),
    intensity: 0.8,
    turbidity: 10,
    rayleigh: 3,
    mieCoefficient: 0.005,
  },
  {
    elevation: 5,
    name: DAY_NIGHT_CYCLE_STAGE.MID_MORNING,
    skyColor: new Color(0xffdab9), // Transitioning towards the brighter midday sky
    lightColor: new Color(0xffdab9),
    intensity: 0.9,
    turbidity: 8,
    rayleigh: 3,
    mieCoefficient: 0.005,
  },
  {
    elevation: 15,
    name: DAY_NIGHT_CYCLE_STAGE.LATE_MORNING,
    skyColor: new Color(0xffffe0), // Near midday but still slightly softer light
    lightColor: new Color(0xffffe0),
    intensity: 0.95,
    turbidity: 6,
    rayleigh: 2,
    mieCoefficient: 0.005,
  },
  {
    elevation: 35,
    name: DAY_NIGHT_CYCLE_STAGE.NOON,
    skyColor: new Color(0xf0ffff), // Bright midday sky
    lightColor: new Color(0xf0ffff),
    intensity: 1.0,
    turbidity: 5,
    rayleigh: 1,
    mieCoefficient: 0.005,
  },
  {
    elevation: 91,
    name: DAY_NIGHT_CYCLE_STAGE.NOON,
    skyColor: new Color(0xf0ffff), // Catch-all for the sun being directly overhead
    lightColor: new Color(0xf0ffff),
    intensity: 1.0,
    turbidity: 5,
    rayleigh: 1,
    mieCoefficient: 0.005,
  },
  {
    elevation: -0.3,
    name: DAY_NIGHT_CYCLE_STAGE.SUNSET,
    skyColor: new Color(0xffa07a),
    lightColor: new Color(0xffa07a),
    intensity: 0.8,
    turbidity: 10,
    rayleigh: 10,
    mieCoefficient: 0.005,
  },
  {
    elevation: -6,
    name: DAY_NIGHT_CYCLE_STAGE.CIVIL_TWILIGHT,
    skyColor: new Color(0xffdab9),
    lightColor: new Color(0xffdab9),
    intensity: 0.5,
    turbidity: 20,
    rayleigh: 2,
    mieCoefficient: 0.002,
  },
  {
    elevation: -12,
    name: DAY_NIGHT_CYCLE_STAGE.NAUTICAL_TWILIGHT,
    skyColor: new Color(0x6495ed),
    lightColor: new Color(0x6495ed),
    intensity: 0.3,
    turbidity: 10,
    rayleigh: 1,
    mieCoefficient: 0.001,
  },
  {
    elevation: -18,
    name: DAY_NIGHT_CYCLE_STAGE.ASTRONOMICAL_TWILIGHT,
    skyColor: new Color(0x483d8b),
    lightColor: new Color(0x483d8b),
    intensity: 0.1,
    turbidity: 6,
    rayleigh: 0.5,
    mieCoefficient: 0.0008,
  },
];
