/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ChairLegs/ChairLegs.glb -t --types --instanceall --output src/models/ChairLegs.tsx
Files: public/models/ChairLegs/ChairLegs.glb [22.52KB] > /Users/andrew/repos/random/random-studio/src/models/models/ChairLegs/ChairLegs.glb [22.5KB] (0%)
*/

import * as THREE from 'three';
import React, { useRef, useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Legs: THREE.Mesh;
  };
  materials: {
    ['SEAT_CASTER.005']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);

export const ChairLegsInstances = ({
  children,
  ...props
}: JSX.IntrinsicElements['group']) => {
  const { nodes } = useGLTF('/models/ChairLegs/ChairLegs.glb') as GLTFResult;

  const instances = useMemo(
    () => ({
      Legs: nodes.Legs,
    }),
    [nodes],
  );

  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => (
        <context.Provider children={children} value={instances} />
      )}
    </Merged>
  );
};

const ChairLegs = (props: JSX.IntrinsicElements['group']) => {
  const instances = useContext(context);

  return (
    <group {...props} dispose={null}>
      <instances.Legs
        position={[-0.047, -0.55, 0.022]}
        rotation={[Math.PI / 2, 0, 1.926]}
        scale={0.032}
      />
    </group>
  );
};

useGLTF.preload('/models/ChairLegs/ChairLegs.glb');
export default ChairLegs;
