/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Mainspace/models/Mainspace/mainspace.gltf -t --types --output src/models/Mainspace.tsx 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube032: THREE.Mesh
    ['Metal_H-Beam001']: THREE.Mesh
    Runway_Wood005: THREE.Mesh
    Plant_pots: THREE.Mesh
    ID549002: THREE.Mesh
    ID549002_1: THREE.Mesh
    GILLIS250: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    Gray: THREE.MeshStandardMaterial
    ['Wood Fine Veneer Oak']: THREE.MeshStandardMaterial
    ['Plaster Lime']: THREE.MeshStandardMaterial
    ['Aluminium Brushed']: THREE.MeshStandardMaterial
    ['Cork Surface']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const Mainspace = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/Mainspace/mainspace.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube032.geometry} material={materials['default']} position={[1.648, -1.746, 3.553]} />
      <mesh geometry={nodes['Metal_H-Beam001'].geometry} material={materials.Gray} position={[2.499, 0.085, 2]} />
      <mesh geometry={nodes.Runway_Wood005.geometry} material={materials['Wood Fine Veneer Oak']} position={[-0.424, -1.972, -5.057]} rotation={[0, -0.262, 0]} />
      <mesh geometry={nodes.Plant_pots.geometry} material={materials['Plaster Lime']} position={[0.068, -1.588, 0.45]} />
      <group position={[-0.051, -1.131, 5.531]}>
        <mesh geometry={nodes.ID549002.geometry} material={materials['Aluminium Brushed']} />
        <mesh geometry={nodes.ID549002_1.geometry} material={materials['Cork Surface']} />
      </group>
      <instancedMesh args={[nodes.GILLIS250.geometry, materials['Wood Fine Veneer Oak'], 5]} instanceMatrix={nodes.GILLIS250.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/Mainspace/mainspace.gltf')
export default Mainspace;
