/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Mainspace/models/Mainspace/mainspace.gltf -t --types --output src/models/Mainspace.tsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { Mesh, MeshStandardMaterial } from 'three';
import useHomeAssistant from '../components/Wonder2/hooks/useHomeAssistant';

type GLTFResult = GLTF & {
  nodes: {
    Cube032: Mesh;
    ['Metal_H-Beam001']: Mesh;
    Runway_Wood005: Mesh;
    Plant_pots: Mesh;
    ID549002: Mesh;
    ID549002_1: Mesh;
    GILLIS250: Mesh;
  };
  materials: {
    ['default']: MeshStandardMaterial;
    Gray: MeshStandardMaterial;
    ['Wood Fine Veneer Oak']: MeshStandardMaterial;
    ['Plaster Lime']: MeshStandardMaterial;
    ['Aluminium Brushed']: MeshStandardMaterial;
    ['Cork Surface']: MeshStandardMaterial;
  };
};

const Mainspace = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(
    '/models/Mainspace/mainspace.gltf',
  ) as GLTFResult;

  const { value } = useHomeAssistant<string>('binary_sensor.knx_alarm_main_2');

  materials['Cork Surface'].roughness = 0;
  materials['Cork Surface'].metalness = 0;

  useFrame(() => {
    if (!materials['Wood Fine Veneer Oak'].map) {
      return;
    }

    if (value === 'off') {
      materials['Wood Fine Veneer Oak'].map.offset.x = 0;

      return;
    }

    materials['Wood Fine Veneer Oak'].map.offset.x += 0.001;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Metal_H-Beam001'].geometry}
        material={materials.Gray}
        position={[2.499, 0.085, 2]}
      />

      <mesh
        geometry={nodes.Runway_Wood005.geometry}
        material={materials['Wood Fine Veneer Oak']}
        position={[-0.424, -1.972, -5.057]}
        rotation={[0, -0.262, 0]}
      />

      <mesh
        geometry={nodes.Plant_pots.geometry}
        material={materials['Plaster Lime']}
        position={[0.068, -1.588, 0.45]}
      />

      <group position={[-0.051, -1.131, 5.531]}>
        <mesh
          geometry={nodes.ID549002.geometry}
          material={materials['Aluminium Brushed']}
        />

        <mesh
          geometry={nodes.ID549002_1.geometry}
          material={materials['Cork Surface']}
        />
      </group>

      <instancedMesh
        args={[nodes.GILLIS250.geometry, materials['Wood Fine Veneer Oak'], 5]}
        // @ts-expect-error Ignore
        instanceMatrix={nodes.GILLIS250.instanceMatrix}
      />
    </group>
  );
};

useGLTF.preload('/models/Mainspace/mainspace.gltf');
export default Mainspace;
