/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Plate/plate.glb -t --types --instanceall --output src/models/Plate.tsx
Files: public/models/Plate/plate.glb [10.29KB] > /Users/andrew/repos/random/random-studio/src/models/models/Plate/plate.glb [10.38KB] (-1%)
*/

import * as THREE from 'three';
import React, { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Kitchen_Plate: THREE.Mesh;
  };
  materials: {
    Kitchen_Plate01: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);

export const PlateInstances = ({
  children,
  ...props
}: JSX.IntrinsicElements['group']) => {
  const { nodes } = useGLTF('/models/Plate/plate.glb') as GLTFResult;

  const instances = useMemo(
    () => ({
      KitchenPlate: nodes.Kitchen_Plate,
    }),
    [nodes],
  );

  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => (
        <context.Provider children={children} value={instances} />
      )}
    </Merged>
  );
};

const Plate = (props: JSX.IntrinsicElements['group']) => {
  const instances = useContext(context);

  return (
    <group {...props} dispose={null}>
      <instances.KitchenPlate position={[3.7, -0.41, 3.7]} scale={0.005} />
    </group>
  );
};

useGLTF.preload('/models/Plate/plate.glb');
export default Plate;
