name: Build Application
on:
  workflow_call:
    inputs:
      MELI_SITE:
        required: true
        type: string
    secrets:
      VIMEO_TOKEN:
        required: true
      NEXT_DATOCMS_API_TOKEN:
        required: true
      MELI_TOKEN:
        required: true
      NEXT_PUBLIC_SUPABASE_URL:
        required: true
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
        required: true
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - uses: gogaille/sparse-checkout@v0.1
        with:
          patterns: public src *.js *.json !cms
      - name: Load cached dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: nextjs-${{ hashFiles('**/package.json') }}
      - name: Load cached build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.videoCache.json
          key: nextjs-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/*.js') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install --dev
      - name: "build"
        run: |
          npm run export
        env:
          NEXT_DATOCMS_API_TOKEN: ${{ secrets.NEXT_DATOCMS_API_TOKEN }}
          VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      - name: "publish"
        run: |
          npx -p "@getmeli/cli" meli upload ./out \
            --url "https://staging.random.studio" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MELI_SITE: ${{ inputs.MELI_SITE }}
