name: Build Application
on:
  workflow_call
jobs:
  prepare:
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_prepare.yml@next.js
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Cache Next
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache # [I]
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: 'build'
        run: |
          npm run build
