name: Clean cache Production
on:
  workflow_dispatch:
jobs:
  clean:
    name: Clean cache
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: 'public'
      SERVER_IP: 195.114.30.143
      SERVER_PORT: 22
      SSH_USERNAME: random-studio
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Gatsby Cache Folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby-260121-3
          restore-keys: |
            ${{ runner.os }}-cache-gatsby-260121-3
      - name: Gatsby Public Folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby
      - name: Clean
        run: npm run clean

