name: Deploy NextJS Staging to Meli
on:
  push:
    branches:
      - "next.js"
env:
  MELI_SITE: '82ece754-578d-42dd-965d-7761523f28ef'
  NEXT_PUBLIC_CDN_URL: 'https://imagedelivery.net/NydGZxxgUj2Qjv652N6Njw'
jobs:
  process-images:
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-images.yml@next.js
  process-vimeo:
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-vimeo.yml@next.js
  build:
    needs: [process-images, process-vimeo]
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_build.yml@next.js
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'publish'
        run: |
          npx -p "@getmeli/cli" meli upload ./out \
            --url "https://staging.random.studio" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
