name: Deploy NextJS Staging to Meli
on:
  push:
    branches:
      - "staging"
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    name: Build and deploy immediately
    uses: RandomStudio/random-studio/.github/workflows/_build-deploy-meli.yml@staging
    with:
      MELI_SITE: "82ece754-578d-42dd-965d-7761523f28ef"
    secrets:
      MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
      NEXT_DATOCMS_API_TOKEN: ${{ secrets.NEXT_DATOCMS_API_TOKEN }}
      VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
