name: Deploy site to Production
on:
  push:
    branches:
      - master
  # Allows external webhook trigger
  repository_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "18.12"
      - uses: gogaille/sparse-checkout@v0.1
        with:
          patterns: public src package.json next.config.js
      - name: Load cached dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: nextjs-${{ hashFiles('**/package.json') }}
      - name: Load cached build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.videoCache.json
          key: nextjs-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/*.js') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install --dev
      - name: "build"
        run: |
          npm run export
        env:
          BUNNY_TOKEN: ${{ secrets.BUNNY_TOKEN }}
          NEXT_DATOCMS_API_TOKEN: ${{ secrets.NEXT_DATOCMS_API_TOKEN }}
          VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
      - name: Deploy to server
        uses: tohn/rsync-deploy@main
        env:
          DEPLOY_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: 22
          FOLDER: "out/"
          SERVER_IP: "195.114.30.143"
          USERNAME: ubuntu
          SERVER_DESTINATION: "/var/www/random.studio/"
