name: Deploy site to Production
on:
  push:
    branches:
      - master
  # Allows external webhook trigger
  repository_dispatch:
jobs:
  failure-notify:
    name: Notify of failure on Slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MSG_AUTHOR: ""
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Random.Studio Github
          SLACK_ICON: https://avatars.githubusercontent.com/u/8861680?s=400&u=c7c52458389708902d47179e1f1a9419196b0420&v=4
          SLACK_COLOR: "#FF0000"
          SLACK_TITLE: Deploy failed
          SLACK_FOOTER: I can't believe you've done this
          MSG_MINIMAL: commit,actions url
