name: Deploy NextJS Staging to Meli
on:
  push:
    branches:
      - "next.js"
jobs:
  process-images:
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-images.yml@next.js
  process-vimeo:
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-vimeo.yml@next.js
  build:
    needs: [process-images, process-vimeo]
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_build.yml@next.js
    secrets:
      MELI_SITE: '82ece754-578d-42dd-965d-7761523f28ef'
      NEXT_PUBLIC_CDN_URL: 'https://imagedelivery.net/NydGZxxgUj2Qjv652N6Njw'
  deploy:
    needs: build
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_deploy.yml@next.js
