name: Deploy site to Production
on:
  push:
    branches:
      - master
  # Allows external webhook trigger
  repository_dispatch:
jobs:
  build:
    name: Build and deploy immediately
    uses: RandomStudio/random-studio/.github/workflows/_build-deploy-production.yml@master
    secrets:
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
      NEXT_DATOCMS_API_TOKEN: ${{ secrets.NEXT_DATOCMS_API_TOKEN }}
      VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
