name: Deploy NextJS Staging to Meli
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "staging"
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show the Github context for the triggered event
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  process-images:
    uses: RandomStudio/random-studio/.github/workflows/_process-images.yml@staging
    secrets:
      RS_BOT_TOKEN: ${{ secrets.RS_BOT_TOKEN }}
  process-vimeo:
    uses: RandomStudio/random-studio/.github/workflows/_process-vimeo.yml@staging
    secrets:
      RS_BOT_TOKEN: ${{ secrets.RS_BOT_TOKEN }}
  build:
    name: Build and deploy immediately
    needs: [process-images, process-vimeo]
    uses: RandomStudio/random-studio/.github/workflows/_build-deploy-meli.yml@staging
    with:
      MELI_SITE: "82ece754-578d-42dd-965d-7761523f28ef"
      NEXT_PUBLIC_CDN_URL: "https://imagedelivery.net/NydGZxxgUj2Qjv652N6Njw"
    secrets:
      MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
