name: Deploy NextJS Staging to Meli
on:
  push:
    branches:
      - "next.js"
jobs:
  build:
    name: Build and deploy immediately
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_build.yml@next.js
    with:
      MELI_SITE: '82ece754-578d-42dd-965d-7761523f28ef'
      NEXT_PUBLIC_CDN_URL: 'https://imagedelivery.net/NydGZxxgUj2Qjv652N6Njw'
    secrets:
      MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
  process-images:
    needs: build
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-images.yml@next.js
  process-vimeo:
    needs: build
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_process-vimeo.yml@next.js
  rebuild-if-required:
    name: Rebuild and deploy with new assets
    if: ${{ needs.process-images.outputs.pushed || needs.process-vimeo.outputs.pushed }}
    needs: [process-images, process-vimeo]
    uses: RandomStudio/random-studio-gatsby/.github/workflows/_build.yml@next.js
    with:
      MELI_SITE: '82ece754-578d-42dd-965d-7761523f28ef'
      NEXT_PUBLIC_CDN_URL: 'https://imagedelivery.net/NydGZxxgUj2Qjv652N6Njw'
    secrets:
      MELI_TOKEN: ${{ secrets.MELI_TOKEN }}

