name: Deploy Production
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: 'public'
      SERVER_IP: 195.114.30.143
      SERVER_PORT: 22
      SSH_USERNAME: random-studio
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Install dependencies
        run: npm install
      - name: Gatsby Cache Folder
        uses: actions/cache@v1
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby-231121
          restore-keys: |
            ${{ runner.os }}-cache-gatsby-231121
      - name: Gatsby Public Folder
        uses: actions/cache@v1
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby
      - name: Build
        run: npm run build
      - name: Create folders
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: mkdir -p /var/www/random.studio
      - name: Deploy to server
        uses: AEnterprise/rsync-deploy@1.0.1
        env:
          ARGS: "-e -c -r --delete"
          DEPLOY_KEY: ${{ env.SSH_KEY }}
          USERNAME: ${{ env.SSH_USERNAME }}
          FOLDER: "${{ env.BUILD_DIR }}/"
          SERVER_DESTINATION: '/var/www/random.studio/'
