name: Synchronise Images to Cloudflare
on:
  push:
    branches:
      - "next.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Checkout into images
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: public/img
      - name: Run changed-files with defaults on the img folder
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          path: public/img
      - name: Upload Images
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            npm run uploadImage -- --file $file
          done
