name: Deploy NextJS Staging to Meli
on:
  push:
    branches:
      - "next.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout into images
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: public/img
      - name: Run changed-files with defaults on the img folder
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          path: public/img
      - name: Upload images
        run: node uploadImages.js --files ${{ steps.changed-files.outputs.added_files }};
