name: Synchronise Images to Cloudflare
on:
  push:
    branches:
      - "next.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Checkout into images
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run changed-files with defaults on the img folder
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          path: public/img
      - name: Upload Images
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            npm run uploadImage -- --file $file
          done
